dynamicPlugins:
  backend:
    backstage.plugin-scaffolder-backend-module-ansible:
      mountPoints:
        - importName: createAnsibleContentAction
          mountPoint: entity.page.overview/cards
