---
name: Export Dynamic Plugin Packages
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: node-version to execute the export
        required: false
        default: '18.x'
      backstage-release:
        description: backstage version to export the dynamic plugins from
        required: false
        default: 'v1.23.4' # corresponds to RHDH 1.1
  push:
    tags: ["v*.*.*"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [18]

    name: Export
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Pack task
        uses: ./.github/actions/pack
        with:
          node-version: ${{ matrix.node-version }}
          plugin: 'scaffolder-backend-module-ansible'