---
name: Release / plugins
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: node-version to execute the export
        required: false
        default: '18.x'
  push:
    tags: ["v*.*.*"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [18]

    name: ðŸš€ / release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: DEBUG - Show GitHub ref tag
        run: echo "${GITHUB_REF##*/}"

      - name: DEBUG - Show GitHub ref tag only version
        run: echo "${GITHUB_REF##*/v}"

      - name: Pack ðŸ“¦ & release ðŸš€
        uses: ./.github/actions/pack
        with:
          node-version: ${{ matrix.node-version }}
